# List

In [1]:
a = [1, 2, 3, 4]
a

[1, 2, 3, 4]

In [3]:
a = list(range(3, 10))
a

[3, 4, 5, 6, 7, 8, 9]

In [4]:
b = [1, 'b', True]
b

[1, 'b', True]

## List comprehension

In [5]:
[i for i in range(1, 5)]

[1, 2, 3, 4]

In [6]:
[i**2 for i in range(1, 5)]

[1, 4, 9, 16]

In [7]:
[i**2 for i in range(1, 5) if i % 2 == 0]

[4, 16]

In [8]:
[i**2 if i % 2 == 0 else i*2 for i in range(1, 5)]

[2, 4, 6, 16]

## Индексация

In [10]:
a

[3, 4, 5, 6, 7, 8, 9]

In [11]:
a[0]

3

In [12]:
a[-1]

9

In [14]:
a[5:]

[8, 9]

In [15]:
a[:5] #.head()

[3, 4, 5, 6, 7]

In [16]:
a[-5:] #.tail(5)

[5, 6, 7, 8, 9]

In [17]:
a[2:6:2]

[5, 7]

In [18]:
a[:6:2]

[3, 5, 7]

In [19]:
a[2::2]

[5, 7, 9]

In [20]:
a[2:6:]

[5, 6, 7, 8]

In [21]:
a[::2]

[3, 5, 7, 9]

In [22]:
a[-1:0:-1]

[9, 8, 7, 6, 5, 4]

In [23]:
a[:2:6]

[3]

In [24]:
a[-1::-1]

[9, 8, 7, 6, 5, 4, 3]

In [25]:
a[::-1]

[9, 8, 7, 6, 5, 4, 3]

In [26]:
a[::]

[3, 4, 5, 6, 7, 8, 9]

In [27]:
b = a[::]
c = a

In [28]:
b

[3, 4, 5, 6, 7, 8, 9]

In [29]:
c

[3, 4, 5, 6, 7, 8, 9]

In [30]:
a

[3, 4, 5, 6, 7, 8, 9]

In [31]:
a[0] = 100

In [32]:
a

[100, 4, 5, 6, 7, 8, 9]

In [33]:
b

[3, 4, 5, 6, 7, 8, 9]

In [34]:
c

[100, 4, 5, 6, 7, 8, 9]

In [35]:
c[1] = 200

In [36]:
c

[100, 200, 5, 6, 7, 8, 9]

In [37]:
a

[100, 200, 5, 6, 7, 8, 9]

# Классы и состояния

sorted(a)  
a.sort()

In [38]:
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [39]:
[x for x in dir(a) if '__' not in x]

['append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [40]:
a.append(100)

In [41]:
a

[100, 200, 5, 6, 7, 8, 9, 100]

In [42]:
a.insert(2, 90)

In [43]:
a

[100, 200, 90, 5, 6, 7, 8, 9, 100]

In [44]:
sorted(a)

[5, 6, 7, 8, 9, 90, 100, 100, 200]

In [45]:
a

[100, 200, 90, 5, 6, 7, 8, 9, 100]

In [46]:
a.sort()

In [47]:
a

[5, 6, 7, 8, 9, 90, 100, 100, 200]

### Что нельзя:

In [48]:
a > 5

TypeError: '>' not supported between instances of 'list' and 'int'

In [49]:
a % 2

TypeError: unsupported operand type(s) for %: 'list' and 'int'

# Матрица

In [50]:
m = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

In [51]:
m

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [52]:
m[::2, ::2]

TypeError: list indices must be integers or slices, not tuple

In [55]:
m[::2][::2]

[[1, 2, 3, 4]]

# NumPy

In [56]:
import numpy as np

In [64]:
m = np.ones(12, dtype='int').cumsum().reshape(3, 4)
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
m[::2, ::2]

array([[ 1,  3],
       [ 9, 11]])

In [66]:
type(m)

numpy.ndarray

## Бинарные маски

In [67]:
m % 3

array([[1, 2, 0, 1],
       [2, 0, 1, 2],
       [0, 1, 2, 0]])

In [69]:
b = m % 4 == 0
b

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]])

In [71]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
m[b]

array([ 4,  8, 12])

## Что может

In [73]:
[x for x in dir(m) if '__' not in x]

['T',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

In [74]:
np.moveaxis(m, 0, 1)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [75]:
m.moveaxis()

AttributeError: 'numpy.ndarray' object has no attribute 'moveaxis'

In [76]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## Броадкастинг

In [79]:
v = np.ones([1, 3], dtype='int').cumsum()
v

array([1, 2, 3])

In [80]:
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
A + v 

array([[2., 2., 3.],
       [1., 3., 3.],
       [1., 2., 4.]])

In [82]:
A.shape, v.shape

((3, 3), (3,))

In [83]:
A + v.T

array([[2., 2., 3.],
       [1., 3., 3.],
       [1., 2., 4.]])

## Быстрое создание

In [84]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [87]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [88]:
np.eye(3) * np.ones(3).cumsum()

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [86]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Pandas

In [89]:
import pandas as pd

In [109]:
data = pd.read_csv('StudentsPerformance.csv')

In [110]:
data.head(10)

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   
5  female        group B          associate's degree      standard   
6  female        group B                some college      standard   
7    male        group B                some college  free/reduced   
8    male        group D                 high school  free/reduced   
9  female        group B                 high school  free/reduced   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75  
5                    none          71             83             78  
6               completed          88             95             92  
7                    none          40             43             39  
8               completed          64             64             67  
9                    none          38             60             50

In [111]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64 
 6   reading score                1000 non-null   int64 
 7   writing score                1000 non-null   int64 
dtypes: int64(3), object(5)
memory usage: 62.6+ KB


In [112]:
data.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [113]:
data.columns = [col.replace(' ', '_').replace('/', '_') for col in data.columns]

In [114]:
data.columns

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score'],
      dtype='object')

In [115]:
data = data.rename(columns={'test_preparation_course':'is_prepared'})
#data.rename(columns={'test_preparation_course':'is_prepared'}, inplace=True)

In [116]:
data.head()

gender race_ethnicity parental_level_of_education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  is_prepared  math_score  reading_score  writing_score  
0        none          72             72             74  
1   completed          69             90             88  
2        none          90             95             93  
3        none          47             57             44  
4        none          76             78             75

In [117]:
data.isna().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
is_prepared                    0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [118]:
data['is_prepared'].unique() 

array(['none', 'completed'], dtype=object)

In [119]:
data['is_prepared'].nunique(dropna=False)

2

In [120]:
data['is_prepared'] = (data['is_prepared'] == 'completed').astype('int')

In [121]:
data.head()

gender race_ethnicity parental_level_of_education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

   is_prepared  math_score  reading_score  writing_score  
0            0          72             72             74  
1            1          69             90             88  
2            0          90             95             93  
3            0          47             57             44  
4            0          76             78             75

In [122]:
data['gender'].value_counts()

female    518
male      482
Name: gender, dtype: int64

### Про связь с NumPy

In [123]:
data.values

array([['female', 'group B', "bachelor's degree", ..., 72, 72, 74],
       ['female', 'group C', 'some college', ..., 69, 90, 88],
       ['female', 'group B', "master's degree", ..., 90, 95, 93],
       ...,
       ['female', 'group C', 'high school', ..., 59, 71, 65],
       ['female', 'group D', 'some college', ..., 68, 78, 77],
       ['female', 'group D', 'some college', ..., 77, 86, 86]],
      dtype=object)

In [124]:
type(data.values)

numpy.ndarray

In [ ]:
{x for x in dir(data) if '_' not in x} - {x for x in dir(m) if '__' not in x}

## Доступ к отдельным элементам

In [127]:
data.head()

gender race_ethnicity parental_level_of_education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

   is_prepared  math_score  reading_score  writing_score  
0            0          72             72             74  
1            1          69             90             88  
2            0          90             95             93  
3            0          47             57             44  
4            0          76             78             75

In [128]:
data.loc[3, 'lunch']

'free/reduced'

In [129]:
data.iloc[3, 3]

'free/reduced'

In [130]:
data.loc[[2, 3, 4], ['gender', 'race_ethnicity', 'lunch']]

gender race_ethnicity         lunch
2  female        group B      standard
3    male        group A  free/reduced
4    male        group C      standard

In [131]:
data.iloc[[2, 3, 4], [0, 1, 3]]

gender race_ethnicity         lunch
2  female        group B      standard
3    male        group A  free/reduced
4    male        group C      standard

In [132]:
data.iloc[[2, 3, 4], [0, 1, 3]].loc[3, 'lunch']

'free/reduced'

In [133]:
data.loc[:, ['gender', 'race_ethnicity']] #data[['gender', 'race_ethnicity']]

gender race_ethnicity
0    female        group B
1    female        group C
2    female        group B
3      male        group A
4      male        group C
..      ...            ...
995  female        group E
996    male        group C
997  female        group C
998  female        group D
999  female        group D

[1000 rows x 2 columns]

In [134]:
data.loc[[2, 5], :] #data.loc[[2, 5], ] или data.loc[[2, 5]]

gender race_ethnicity parental_level_of_education     lunch  is_prepared  \
2  female        group B             master's degree  standard            0   
5  female        group B          associate's degree  standard            0   

   math_score  reading_score  writing_score  
2          90             95             93  
5          71             83             78

In [135]:
data['gender']

0      female
1      female
2      female
3        male
4        male
        ...  
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [136]:
data.gender

0      female
1      female
2      female
3        male
4        male
        ...  
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [137]:
data[['gender', 'race_ethnicity']]

gender race_ethnicity
0    female        group B
1    female        group C
2    female        group B
3      male        group A
4      male        group C
..      ...            ...
995  female        group E
996    male        group C
997  female        group C
998  female        group D
999  female        group D

[1000 rows x 2 columns]

## Доступ по булевой маске

In [138]:
temp = data.iloc[:4, 4:8]
temp

is_prepared  math_score  reading_score  writing_score
0            0          72             72             74
1            1          69             90             88
2            0          90             95             93
3            0          47             57             44

In [139]:
temp.loc[[True, True, False, True]] # temp[[True, True, False, True]]

is_prepared  math_score  reading_score  writing_score
0            0          72             72             74
1            1          69             90             88
3            0          47             57             44

In [140]:
temp.loc[[True, True, False, True], [False, True, False, True]]

math_score  writing_score
0          72             74
1          69             88
3          47             44

In [141]:
temp.loc[temp.reading_score > 80]

is_prepared  math_score  reading_score  writing_score
1            1          69             90             88
2            0          90             95             93

## Фильтрация

In [142]:
data.head()

gender race_ethnicity parental_level_of_education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

   is_prepared  math_score  reading_score  writing_score  
0            0          72             72             74  
1            1          69             90             88  
2            0          90             95             93  
3            0          47             57             44  
4            0          76             78             75

In [144]:
is_female = data['gender'] == 'female'
is_male = ~is_female

In [145]:
is_male

0      False
1      False
2      False
3       True
4       True
       ...  
995    False
996     True
997    False
998    False
999    False
Name: gender, Length: 1000, dtype: bool

In [146]:
is_bachelor = data['parental_level_of_education'] == "bachelor's degree"
is_master = data['parental_level_of_education'] == "master's degree"

In [153]:
data.loc[is_female & is_bachelor][['math_score', 'reading_score', 'writing_score']].mean()

math_score       68.349206
reading_score    77.285714
writing_score    78.380952
dtype: float64